
server:
  port: 3000
  servlet:
    context-path: /auth-server

spring:
  profiles:
    default: default
  application:
    name: api-auth-server
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
    password: Peru123.
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/rrhhcompany
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

